#ifndef _DEFS
#define _DEFS

enum eASCII_COLORS{COLOR_BLACK, COLOR_WHITE, COLOR_B_WHITE, COLOR_RED, COLOR_B_RED, COLOR_BLUE,
                   COLOR_B_BLUE, COLOR_GREEN, COLOR_B_GREEN, COLOR_CYAN, COLOR_B_CYAN, COLOR_MAGENTA,
                   COLOR_B_MAGENTA, COLOR_YELLOW, COLOR_B_YELLOW, COLOR_TOTAL};

enum _GAMEOBJTYPES{OBJ_NONE, OBJ_MAPTILE, OBJ_TOTAL};

#endif // _DEFS
